version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: judging_system
      MYSQL_USER: judge_app
      MYSQL_PASSWORD: securepass
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: