version: '3.8'

services:
  app:
    build:
      context: .
      args:
        APACHE_UID: 1000  # Match your host user ID (run `id -u` to check)
        APACHE_GID: 1000  # Match your host group ID (run `id -g` to check)
    ports:
      - "8000:80"
    volumes:
      - /home/melody/Desktop/judging-system:/var/www/html
    environment:
      - APACHE_UID=1000
      - APACHE_GID=1000
    restart: unless-stopped
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: judging_system
      MYSQL_USER: melody
      MYSQL_PASSWORD: melody123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: