version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_NAME=judging_system
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: judging_system
      MYSQL_USER: judging_user
      MYSQL_PASSWORD: SecurePassword123!


      